### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by d4nm0** [KifKick/homebridge-proxmox#50]
I did the configuration of the plugin and I have this error in the console: 07/03/2023, 23:30:13HOOBSWARNINGunhandled rejection: Error: Auth https://192.168.1.61:8006/api2/json/access/ticket Failed!

`{
    "platform": "HomebridgeProxmox",
    "username": "root",
    "password": "password",
    "host": "192.168.x.xx"
}`

**Comment by KifKick** [comment]
Add `"ssl": true,` to your config and let me know @d4nm0 

Btw, my login look like `"username": "root@pam",`

**Comment by d4nm0** [comment]
what is pam ?

**Comment by KifKick** [comment]
Method of login to your proxmox dashboard.

**Comment by d4nm0** [comment]
ok, i have this error : unhandled rejection: Error: Auth https://192.168.XXX.XXX:8006/api2/json/access/ticket Failed!

**Comment by d4nm0** [comment]
ok it's good with @pam and ssl true :)

**Comment by d4nm0** [comment]
ok it's good with @pam and ssl true :)
